# Generated by Django 5.2.11 on 2026-05-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0003_transaction_address_transaction_pic_at_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='awb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
