# Generated by Django 5.2.11 on 2026-05-18 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0004_product_awb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_add_product', 'Can add product'), ('can_edit_product', 'Can edit product'), ('can_delete_product', 'Can delete product'), ('can_bulk_import', 'Can bulk import products via CSV')]},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': [('can_create_transaction', 'Can create Surat Jalan')]},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
