# Generated by Django 5.2.11 on 2026-06-09 03:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0007_add_rollback_fields_and_fixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activitylog',
            name='gudang_acti_timesta_5ab283_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='gudang_tran_created_e1518f_idx',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sdr_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['timestamp'], name='gudang_acti_timesta_d1dba3_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='gudang_tran_created_cb0a78_idx'),
        ),
    ]
