# Generated by Django 5.2.11 on 2026-06-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0008_remove_activitylog_gudang_acti_timesta_5ab283_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
    ]
