# Generated by Django 5.2.11 on 2026-07-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0011_product_is_reserved_product_reserved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingnote',
            name='po_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
